<?php
$this->load->helper('cookie');
$this->load->view('include/header',$title);
$this->load->view('include/top-mpr',$extra);
$this->load->view($main_content,$title,$extra);
$this->load->view('include/footer');
/*$this->load->view('include/navigation-menu-pos',$title);
$this->load->view($main_content,$extra);
$this->load->view('include/footer');*/
