name: Build and Deploy

on:
  push:
    branches:
    - main
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      deploy-action:
        description: "Environment to deploy to"
        required: true
        default: "deploy-stg"
        type: choice
        options:
        - "deploy-stg"
        - "deploy-prod"
jobs:
  stg:
    if: github.event.inputs.deploy-action == 'deploy-stg' || github.event_name == 'push' || github.ref_name == 'main'
    runs-on: [self-hosted, qn-stg-erp-app]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build --tag qn_erp_sme:$GITHUB_REF_NAME-$GITHUB_SHA .

    - name: Deploy
      env:
        BASE_URL: ${{ vars.BASE_URL }}
        DB_HOST: ${{ vars.DB_HOST_SME_STG }}
        DB_USERNAME: ${{ vars.DB_USERNAME_SME_STG }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD_SME_STG }}
        DB_NAME: ${{ vars.DB_NAME_SME_STG }}
        EMPTY_DB_NAME: ${{ vars.EMPTY_DB_NAME_SME_STG }}
        BUCKET_NAME: ${{ vars.BUCKET_NAME_SME_STG }}
        BUCKET_REGION: ${{ vars.BUCKET_REGION_SME_STG }}
        BUCKET_ACCESS_KEY: ${{ vars.BUCKET_ACCESS_KEY_SME_STG }}
        BUCKET_SECRET_KEY: ${{ secrets.BUCKET_SECRET_KEY_SME_STG }}
      run: |
        cd /opt/qn_erp_sme
        docker compose -f docker-compose.yml up -d
        docker ps
  prod:
    if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.deploy-action == 'deploy-prod'
    runs-on: [self-hosted, qn-prod-erp-app]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build --tag qn_erp_sme:$GITHUB_REF_NAME-$GITHUB_SHA .

    - name: Deploy
      env:
        BASE_URL: ${{ vars.BASE_URL }}
        DB_HOST: ${{ vars.DB_HOST_SME_PROD }}
        DB_USERNAME: ${{ vars.DB_USERNAME_SME_PROD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD_SME_PROD }}
        DB_NAME: ${{ vars.DB_NAME_SME_PROD }}
        EMPTY_DB_NAME: ${{ vars.EMPTY_DB_NAME_SME_PROD }}
        BUCKET_NAME: ${{ vars.BUCKET_NAME_SME_PROD }}
        BUCKET_REGION: ${{ vars.BUCKET_REGION_SME_PROD }}
        BUCKET_ACCESS_KEY: ${{ vars.BUCKET_ACCESS_KEY_SME_PROD }}
        BUCKET_SECRET_KEY: ${{ secrets.BUCKET_SECRET_KEY_SME_PROD }}
      run: |
        cd /opt/qn_erp_sme_prod
        docker compose -f docker-compose.yml up -d
        docker ps

